// 이 파일은 자동 생성 파일입니다. 직접 수정하지 마세요!
export const iconNames = [
  'ic_ai',
  'ic_ai_blue',
  'ic_ai_gra',
  'ic_ai_white',
  'ic_allmemo',
  'ic_allmemo_blue',
  'ic_cardview_off',
  'ic_cardview_on',
  'ic_close',
  'ic_file',
  'ic_folding',
  'ic_img',
  'ic_label',
  'ic_label_blue',
  'ic_memo_blue',
  'ic_newmemo',
  'ic_newmemo_blue',
  'ic_output',
  'ic_output_blue',
  'ic_pdf',
  'ic_profile',
  'ic_search',
  'ic_trash',
  'ic_trash_blue',
  'ic_treeview_off',
  'ic_treeview_on',
] as const;
export type IconName = (typeof iconNames)[number];
